### ISSUE TITLE
Get setting from explicit ContentReference

### ISSUE THREAD

**Issue by heinzmuller** [LinusEkstrom/AddOn.Episerver.Settings#38]
There are cases where you might want nested settings and it would be nice to be able to have an API/method to get that specific setting without relying on naming conventions.

What you need to do today
```csharp
var startPage = _contentLoader.Get<StartPage>(ContentReference.StartPage);
var settings = _settingsService.GetSettings<SiteSettings>(startPage);
var footer = _settingsService.GetSettings<SiteFooterSettings>(settings);
```

Proposal/suggestion
```csharp
var startPage = _contentLoader.Get<StartPage>(ContentReference.StartPage);
var settings = _settingsService.GetSettings<SiteSettings>(startPage.Settings);
var footer = _settingsService.GetSettings<SiteFooterSettings>(settings.Footer);
```

**Comment by LinusEkstrom** [comment]
I think that we have briefly talked about getting typed support for getting settings @vansterhant, but I don't recollect if we hade any good ideas, specifically that would also handle the recursive support?

**Comment by vansterhant** [comment]
As Linus mentioned, the tricky part is to get the hierarchical lookup to know what to do. As done in the proposal we will not know what to look for if the property that is pointed out is null. And if one simply wants to load settings from known ContentReferences there is no need to use the getSettings() at all. One can just use the ContentLoader:

```
var footer = _contentLoader.Get<SiteFooterSettings>(settings.Footer);
```

For the nested setting that must be the recommended way, @LinusEkstrom ? Since it will try to traverse the block hierarchy tree otherwise?

I tried out adding support for expressions(like PropertyFor), but it ends up being a rather clumsy API since it needs to know the types of both the content in and the setting out. 

`GetSettings<MyPage, MySetting>(page, x => x.MySettingsProp);`

This is since the prop will always be a ContentReference and not an actual setting, so the compiler can't deduce the types from the expression.

The cleanest idea I've come up with to have hierarchical lookup work without relying on a naming convention while having some kind of type safety is to add an API so that one can call like:

`_settingsService.GetSettings<SiteSettings>(settings, nameof(settings.Footer));`

If on c# 10 one could maybe use [CallerArgumentExpression] but would still need to pass in both the page and the property otherwise there is no way to tell where we are in the hierarchy.

**Comment by LinusEkstrom** [comment]
I agree @vansterhant ; I think that using nameof is currently the best solution for this without adding additional complexity. If you want to be explicit you can always implement an interface yourself for each setting and implement this for each content type that implements this setting and use the name in the property in the interface when making calls. That should be possible to do without adding additional support in the core system.
